import assert from "node:assert/strict";
import test from "node:test";
import pg from "pg";
import { readPostgresFingerprintCompatibility, readPostgresSnapshot } from "./catalog";
import { fingerprintSnapshot } from "./fingerprint";
import { pinFingerprintEnvironment } from "./fingerprint-transaction";
import { readOnlyQueryLayer } from "./read-only-query";

if (process.env.SCHEMA_DRIFT_DISPOSABLE_DB !== "1" || !process.env.DATABASE_URL) {
  throw new Error(
    "Golden DDL fixture refused: set DATABASE_URL and SCHEMA_DRIFT_DISPOSABLE_DB=1 explicitly",
  );
}

test("PostgreSQL 16 DDL golden fixture on a proven disposable database", async () => {
  const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL, max: 1 });
  const client = await pool.connect();
  const database = await client.query("SELECT pg_catalog.current_database() AS name");
  const databaseName = String(database.rows[0]?.name);
  if (!/(?:^|_)(?:test|disposable)(?:_|$)/i.test(databaseName)) {
    client.release();
    await pool.end();
    throw new Error(`Golden DDL fixture refused for non-disposable database: ${databaseName}`);
  }
  const fixture = "schema_fingerprint_pg16_golden_fixture";
  const enumName = `${fixture}_status`;
  const emptyEnumName = `${fixture}_empty_status`;
  const functionName = `${fixture}_guard`;
  const whenTriggerName = `${fixture}_when`;
  const constraintTriggerName = `${fixture}_constraint`;
  try {
    await client.query("BEGIN");
    await client.query(`CREATE TYPE public.${enumName} AS ENUM ('', 'queued')`);
    await client.query(`CREATE TYPE public.${emptyEnumName} AS ENUM ()`);
    await client.query(`CREATE TABLE public.${fixture} (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      label text, amount integer NOT NULL DEFAULT 7, active boolean NOT NULL DEFAULT true,
      status public.${enumName} NOT NULL DEFAULT ''::public.${enumName},
      period int4range NOT NULL,
      CONSTRAINT ${fixture}_label_unique UNIQUE NULLS NOT DISTINCT (label) INCLUDE (amount),
      CONSTRAINT ${fixture}_amount_check CHECK (amount >= 0),
      CONSTRAINT ${fixture}_period_exclude EXCLUDE USING gist (period WITH &&))`);
    await client.query(`CREATE INDEX ${fixture}_expression_include_idx
      ON public.${fixture} ((lower(label))) INCLUDE (amount) WHERE active`);
    await client.query(`CREATE FUNCTION public.${functionName}() RETURNS trigger
      LANGUAGE plpgsql AS $body$
      BEGIN
        RETURN NEW;
      END
      $body$`);
    await client.query(`CREATE TRIGGER ${whenTriggerName}
      BEFORE UPDATE OF amount ON public.${fixture}
      FOR EACH ROW WHEN (OLD.amount IS DISTINCT FROM NEW.amount)
      EXECUTE FUNCTION public.${functionName}('audit')`);
    await client.query(`CREATE CONSTRAINT TRIGGER ${constraintTriggerName}
      AFTER UPDATE ON public.${fixture}
      DEFERRABLE INITIALLY IMMEDIATE FOR EACH ROW
      EXECUTE FUNCTION public.${functionName}('constraint')`);
    await pinFingerprintEnvironment(client);
    const readOnly = readOnlyQueryLayer(client);
    const compatibility = await readPostgresFingerprintCompatibility(readOnly);
    const snapshot = await readPostgresSnapshot(readOnly);
    const table = snapshot.tables.find((value) => value.name === fixture);
    assert.ok(table);
    const enums = snapshot.enums?.filter((value) =>
      value.name === enumName || value.name === emptyEnumName);
    assert.deepEqual(enums, [
      { schema: "public", name: emptyEnumName, labels: [] },
      { schema: "public", name: enumName, labels: ["", "queued"] },
    ]);
    const triggers = snapshot.triggers?.filter((value) => value.tableName === fixture);
    assert.equal(triggers?.length, 2);
    const triggerContract = triggers?.map((value) => ({
      name: value.name,
      enabled: value.enabled,
      timing: value.timing,
      events: value.events,
      updateColumns: value.updateColumns,
      level: value.level,
      when: value.when,
      constraint: value.constraint,
      deferrable: value.deferrable,
      initiallyDeferred: value.initiallyDeferred,
      functionSchema: value.functionSchema,
      functionName: value.functionName,
      argumentsBase64: value.argumentsBase64,
    }));
    assert.deepEqual(triggerContract, [
      {
        name: constraintTriggerName, enabled: "origin", timing: "after",
        events: ["update"], updateColumns: [], level: "row", when: null,
        constraint: true, deferrable: true, initiallyDeferred: false,
        functionSchema: "public", functionName, argumentsBase64: "Y29uc3RyYWludAA=",
      },
      {
        name: whenTriggerName, enabled: "origin", timing: "before",
        events: ["update"], updateColumns: ["amount"], level: "row",
        when: '("old"."amount" IS DISTINCT FROM "new"."amount")',
        constraint: false, deferrable: false, initiallyDeferred: false,
        functionSchema: "public", functionName, argumentsBase64: "YXVkaXQA",
      },
    ]);
    for (const trigger of triggers ?? []) {
      assert.match(trigger.definition, /^CREATE (?:CONSTRAINT )?TRIGGER /);
      assert.match(trigger.functionDefinition, /BEGIN\s+RETURN NEW;\s+END/s);
    }
    const result = fingerprintSnapshot({
      tables: [table],
      enums,
      triggers,
      unmodelled: {
        views: [], materializedViews: [], foreignTables: [], sequences: [],
        applicationSchemas: [], rlsTables: [], policies: [], extensions: [],
      },
    }, [], compatibility);
    assert.match(result.structuralFingerprint, /^[a-f0-9]{64}$/);
    assert.match(result.physicalFingerprint, /^[a-f0-9]{64}$/);
    assert.notEqual(result.structuralFingerprint, result.physicalFingerprint);
    const changedBody = structuredClone({
      tables: [table], enums, triggers,
      unmodelled: result.unmodelledObjectCensus,
    });
    changedBody.triggers![0]!.functionDefinition += "\n-- reviewed mutation";
    const changedBodyResult = fingerprintSnapshot(changedBody, [], compatibility);
    assert.notEqual(changedBodyResult.structuralFingerprint, result.structuralFingerprint);
    assert.notEqual(changedBodyResult.physicalFingerprint, result.physicalFingerprint);
    const renamed = structuredClone({
      tables: [table], enums, triggers,
      unmodelled: result.unmodelledObjectCensus,
    });
    renamed.triggers![0]!.name = `${constraintTriggerName}_renamed`;
    renamed.triggers![0]!.definition = renamed.triggers![0]!.definition.replace(
      constraintTriggerName,
      `${constraintTriggerName}_renamed`,
    );
    const renamedResult = fingerprintSnapshot(renamed, [], compatibility);
    assert.notEqual(renamedResult.structuralFingerprint, result.structuralFingerprint);
    assert.notEqual(renamedResult.physicalFingerprint, result.physicalFingerprint);
  } finally {
    await client.query("ROLLBACK").catch(() => undefined);
    client.release();
    await pool.end();
  }
});