import assert from "node:assert/strict";
import test from "node:test";
import pg from "pg";
import { readPostgresFingerprintCompatibility, readPostgresSnapshot } from "./catalog";
import { fingerprintSnapshot } from "./fingerprint";
import { beginFingerprintTransaction } from "./fingerprint-transaction";
import { ownershipExceptions } from "./ownership";
import { readOnlyQueryLayer } from "./read-only-query";

if (!process.env.DATABASE_URL && process.env.SCHEMA_DRIFT_UNIT_ONLY !== "1") {
  throw new Error("DATABASE_URL is required for fingerprint integration tests; set SCHEMA_DRIFT_UNIT_ONLY=1 to skip deliberately");
}

test("current database fingerprint is stable across three read-only catalog reads", {
  skip: process.env.SCHEMA_DRIFT_UNIT_ONLY === "1",
}, async () => {
  const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL, max: 1 });
  try {
    const results = [];
    const initialSettings = [
      { searchPath: "public, pg_catalog", intervalStyle: "postgres", dateStyle: "ISO, MDY", timeZone: "Europe/Belgrade" },
      { searchPath: "pg_catalog", intervalStyle: "iso_8601", dateStyle: "SQL, DMY", timeZone: "UTC" },
      { searchPath: "\"$user\", public", intervalStyle: "sql_standard", dateStyle: "Postgres, YMD", timeZone: "America/New_York" },
    ];
    for (let run = 0; run < 3; run += 1) {
      const client = await pool.connect();
      try {
        const settings = initialSettings[run]!;
        await client.query(`SET SESSION search_path = ${settings.searchPath}`);
        await client.query(`SET SESSION IntervalStyle = '${settings.intervalStyle}'`);
        await client.query(`SET SESSION DateStyle = '${settings.dateStyle}'`);
        await client.query(`SET SESSION TimeZone = '${settings.timeZone}'`);
        await beginFingerprintTransaction(client);
        const readOnlyClient = readOnlyQueryLayer(client);
        const postgresCompatibility = await readPostgresFingerprintCompatibility(readOnlyClient);
        results.push(fingerprintSnapshot(
          await readPostgresSnapshot(readOnlyClient),
          ownershipExceptions,
          postgresCompatibility,
        ));
        await client.query("COMMIT");
      } catch (error) {
        await client.query("ROLLBACK").catch(() => undefined);
        throw error;
      } finally {
        client.release();
      }
    }
    assert.equal(results[0]!.structuralFingerprint, results[1]!.structuralFingerprint);
    assert.equal(results[1]!.structuralFingerprint, results[2]!.structuralFingerprint);
    assert.equal(results[0]!.physicalFingerprint, results[1]!.physicalFingerprint);
    assert.equal(results[1]!.physicalFingerprint, results[2]!.physicalFingerprint);
  } finally {
    await pool.end();
  }
});

test("PostgreSQL 16 catalog deparser matches the reviewed golden fixture", {
  skip: process.env.SCHEMA_DRIFT_UNIT_ONLY === "1",
}, async () => {
  const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL, max: 1 });
  const fixtureName = "schema_fingerprint_pg16_golden_fixture";
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    await client.query(`
      CREATE TABLE public.${fixtureName} (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        label text,
        amount integer NOT NULL DEFAULT 7,
        active boolean NOT NULL DEFAULT true,
        period int4range NOT NULL,
        CONSTRAINT ${fixtureName}_label_unique
          UNIQUE NULLS NOT DISTINCT (label) INCLUDE (amount),
        CONSTRAINT ${fixtureName}_amount_check CHECK (amount >= 0),
        CONSTRAINT ${fixtureName}_period_exclude
          EXCLUDE USING gist (period WITH &&)
      )`);
    await client.query(`
      CREATE INDEX ${fixtureName}_expression_include_idx
      ON public.${fixtureName} ((lower(label))) INCLUDE (amount)
      WHERE active`);

    const readOnlyClient = readOnlyQueryLayer(client);
    const postgresCompatibility = await readPostgresFingerprintCompatibility(readOnlyClient);
    const catalog = await readPostgresSnapshot(readOnlyClient);
    const fixture = catalog.tables.find((table) => table.name === fixtureName);
    assert.ok(fixture, "golden fixture must be present in the catalog snapshot");
    const result = fingerprintSnapshot({ tables: [fixture] }, [], postgresCompatibility);

    assert.equal(
      result.structuralFingerprint,
      "31bd07e7587a9b9bb55645e26b00c6136b2d3af5c9156e7441d728923956d779",
    );
    assert.equal(
      result.physicalFingerprint,
      "2774e7d10a1ca58a4d9ef9e77552210d6f0ab8b4691788402a2c00ef2a2aae53",
    );
  } finally {
    await client.query("ROLLBACK").catch(() => undefined);
    client.release();
    await pool.end();
  }
});