import { Router, type IRouter } from "express";
import { and, asc, eq, gt, inArray, lt, sql } from "drizzle-orm";
import { z } from "zod";
import { db, coursesTable, courseEnrollmentsTable, courseSessionsTable, educationAttendanceTable, educationBundlesTable, educationBundleCoursesTable, educationBundlePurchasesTable, educationCenterReviewsTable, educationCentersTable, educationCenterStaffTable, educationContactHistoryTable, educationInventoryItemsTable, educationInventoryMovementsTable, educationResourcesTable, educationSessionResourcesTable, employeesTable, productsTable, usersTable } from "@workspace/db";
import { getCurrentUser, isAdmin } from "../lib/auth";
const router: IRouter = Router();
const bad = (res: any, error: string) => res.status(400).json({ error });
const resourceView = (row: any) => ({ ...row, type: row.kind, kind: undefined });
const inventoryView = (row: any) => ({ ...row, quantity: row.quantityOnHand, quantityOnHand: undefined, unit: "kom" });
const bundleView = (row: any) => ({ ...row, name: row.title, title: undefined });
async function access(req: any, res: any, centerId: string) {
  const user = await getCurrentUser(req); if (!user) { res.status(401).json({ error: "Prijava je obavezna." }); return null; }
  if (isAdmin(user)) return user;
  const [center] = await db.select().from(educationCentersTable).where(eq(educationCentersTable.id, centerId)).limit(1);
  const [staff] = await db.select().from(educationCenterStaffTable).where(and(eq(educationCenterStaffTable.centerId, centerId), eq(educationCenterStaffTable.userId, user.id), eq(educationCenterStaffTable.active, true), inArray(educationCenterStaffTable.role, ["owner_admin", "manager_reception"]))).limit(1);
  if (center?.ownerId !== user.id && !staff) { res.status(403).json({ error: "Nemate pravo upravljanja podacima ovog edukativnog centra." }); return null; } return user;
}
router.get("/education/centers/:centerId/resources", async (req,res) => { if (!await access(req,res,req.params.centerId)) return; res.json((await db.select().from(educationResourcesTable).where(eq(educationResourcesTable.centerId,req.params.centerId)).orderBy(asc(educationResourcesTable.name))).map(resourceView)); });
router.post("/education/centers/:centerId/resources", async (req,res) => { if (!await access(req,res,req.params.centerId)) return; const p=z.object({type:z.enum(["room","equipment"]),name:z.string().min(1).max(160),capacity:z.number().int().nonnegative().nullable().optional()}).safeParse(req.body); if(!p.success)return bad(res,"Podaci resursa nisu ispravni."); const [row]=await db.insert(educationResourcesTable).values({kind:p.data.type,name:p.data.name,centerId:req.params.centerId,capacity:p.data.capacity??null}).returning(); res.status(201).json(resourceView(row)); });
router.patch("/education/centers/:centerId/resources/:id", async (req,res) => { if (!await access(req,res,req.params.centerId)) return; const p=z.object({name:z.string().min(1).max(160).optional(),capacity:z.number().int().nonnegative().nullable().optional(),active:z.boolean().optional()}).safeParse(req.body); if(!p.success)return bad(res,"Podaci resursa nisu ispravni."); const [row]=await db.update(educationResourcesTable).set({...p.data,updatedAt:new Date()}).where(and(eq(educationResourcesTable.id,req.params.id),eq(educationResourcesTable.centerId,req.params.centerId))).returning(); if(!row)return res.status(404).json({error:"Resurs nije pronađen."});res.json(resourceView(row)); });
router.post("/education/centers/:centerId/sessions/:sessionId/resources", async(req,res)=>{ if(!await access(req,res,req.params.centerId))return;const p=z.object({resourceId:z.string().uuid(),quantity:z.number().int().positive().default(1)}).safeParse(req.body);if(!p.success)return bad(res,"Dodela resursa nije ispravna."); const [session]=await db.select({startsAt:courseSessionsTable.startsAt,endsAt:courseSessionsTable.endsAt}).from(courseSessionsTable).innerJoin(coursesTable,eq(coursesTable.id,courseSessionsTable.courseId)).where(and(eq(courseSessionsTable.id,req.params.sessionId),eq(coursesTable.centerId,req.params.centerId))).limit(1);const [resource]=await db.select().from(educationResourcesTable).where(and(eq(educationResourcesTable.id,p.data.resourceId),eq(educationResourcesTable.centerId,req.params.centerId),eq(educationResourcesTable.active,true))).limit(1);if(!session||!resource)return res.status(404).json({error:"Termin ili resurs nije pronađen."}); const conflicts=await db.select({id:educationSessionResourcesTable.id}).from(educationSessionResourcesTable).innerJoin(courseSessionsTable,eq(courseSessionsTable.id,educationSessionResourcesTable.sessionId)).where(and(eq(educationSessionResourcesTable.resourceId,p.data.resourceId),lt(courseSessionsTable.startsAt,session.endsAt),gt(courseSessionsTable.endsAt,session.startsAt)));if(conflicts.length)return res.status(409).json({error:"Resurs je već zauzet u izabranom terminu."});const [row]=await db.insert(educationSessionResourcesTable).values({sessionId:req.params.sessionId,...p.data}).returning();res.status(201).json(row);});
router.get("/education/centers/:centerId/inventory",async(req,res)=>{if(!await access(req,res,req.params.centerId))return;res.json((await db.select().from(educationInventoryItemsTable).where(eq(educationInventoryItemsTable.centerId,req.params.centerId))).map(inventoryView));});
router.post("/education/centers/:centerId/inventory",async(req,res)=>{if(!await access(req,res,req.params.centerId))return;const p=z.object({name:z.string().min(1),productId:z.string().uuid().nullable().optional(),quantity:z.number().int().min(0),unit:z.string().min(1),reorderLevel:z.number().int().min(0).default(0)}).safeParse(req.body);if(!p.success)return bad(res,"Stavka zaliha nije ispravna.");if(p.data.productId&&!(await db.select().from(productsTable).where(and(eq(productsTable.id,p.data.productId),eq(productsTable.active,true),eq(productsTable.professionalEnabled,true))).limit(1)).length)return bad(res,"B2B proizvod nije pronađen ili nije dostupan.");const [row]=await db.insert(educationInventoryItemsTable).values({name:p.data.name,quantityOnHand:p.data.quantity,reorderLevel:p.data.reorderLevel,centerId:req.params.centerId,productId:p.data.productId??null}).returning();res.status(201).json(inventoryView(row));});
router.post("/education/centers/:centerId/inventory/:id/movements",async(req,res)=>{const user=await access(req,res,req.params.centerId);if(!user)return;const p=z.object({delta:z.number().int().refine(x=>x!==0),note:z.string().min(1),courseId:z.string().uuid().nullable().optional(),sessionId:z.string().uuid().nullable().optional()}).safeParse(req.body);if(!p.success)return bad(res,"Kretanje zaliha nije ispravno.");const result=await db.transaction(async tx=>{const [item]=await tx.select().from(educationInventoryItemsTable).where(and(eq(educationInventoryItemsTable.id,req.params.id),eq(educationInventoryItemsTable.centerId,req.params.centerId))).for("update").limit(1);if(!item||item.quantityOnHand+p.data.delta<0)throw new Error("STOCK");if(p.data.courseId){const [course]=await tx.select({id:coursesTable.id}).from(coursesTable).where(and(eq(coursesTable.id,p.data.courseId),eq(coursesTable.centerId,req.params.centerId))).limit(1);if(!course)throw new Error("LINK");}if(p.data.sessionId){const [session]=await tx.select({courseId:courseSessionsTable.courseId}).from(courseSessionsTable).innerJoin(coursesTable,eq(coursesTable.id,courseSessionsTable.courseId)).where(and(eq(courseSessionsTable.id,p.data.sessionId),eq(coursesTable.centerId,req.params.centerId))).limit(1);if(!session||p.data.courseId&&session.courseId!==p.data.courseId)throw new Error("LINK");}await tx.update(educationInventoryItemsTable).set({quantityOnHand:item.quantityOnHand+p.data.delta}).where(eq(educationInventoryItemsTable.id,item.id));return (await tx.insert(educationInventoryMovementsTable).values({...p.data,centerId:req.params.centerId,itemId:item.id,actorUserId:user.id,courseId:p.data.courseId??null,sessionId:p.data.sessionId??null}).returning())[0];}).catch(()=>null);if(!result)return res.status(409).json({error:"Nema dovoljno zaliha, stavka ili veza sa kursom nije ispravna."});res.status(201).json(result);});
router.get("/education/centers/:centerId/bundles",async(req,res)=>{if(!await access(req,res,req.params.centerId))return;res.json((await db.select().from(educationBundlesTable).where(eq(educationBundlesTable.centerId,req.params.centerId))).map(bundleView));});
router.post("/education/centers/:centerId/bundles",async(req,res)=>{if(!await access(req,res,req.params.centerId))return;const p=z.object({name:z.string().min(1),description:z.string().default(""),price:z.number().int().min(0),active:z.boolean().default(true),published:z.boolean().default(false),courseIds:z.array(z.string().uuid()).default([])}).safeParse(req.body);if(!p.success)return bad(res,"Paket nije ispravan.");const courses=await db.select({id:coursesTable.id}).from(coursesTable).where(and(eq(coursesTable.centerId,req.params.centerId),inArray(coursesTable.id,p.data.courseIds),eq(coursesTable.published,true),eq(coursesTable.archived,false)));if(courses.length!==p.data.courseIds.length)return bad(res,"Paket može sadržati samo aktivne kurseve ovog centra.");if(p.data.published&&(!p.data.active||!courses.length))return bad(res,"Objavljen paket mora imati najmanje jedan aktivan kurs centra.");const row=await db.transaction(async tx=>{const [bundle]=await tx.insert(educationBundlesTable).values({title:p.data.name,description:p.data.description,price:p.data.price,active:p.data.active,published:p.data.published,centerId:req.params.centerId}).returning();if(p.data.courseIds.length)await tx.insert(educationBundleCoursesTable).values(p.data.courseIds.map((courseId,sortOrder)=>({bundleId:bundle.id,courseId,sortOrder})));return bundle;});res.status(201).json(bundleView(row));});
router.patch("/education/centers/:centerId/bundles/:id",async(req,res)=>{if(!await access(req,res,req.params.centerId))return;const p=z.object({name:z.string().min(1).optional(),description:z.string().optional(),price:z.number().int().min(0).optional(),active:z.boolean().optional(),published:z.boolean().optional(),courseIds:z.array(z.string().uuid()).optional()}).safeParse(req.body);if(!p.success)return bad(res,"Izmene paketa nisu ispravne.");const row=await db.transaction(async tx=>{const [existing]=await tx.select().from(educationBundlesTable).where(and(eq(educationBundlesTable.id,req.params.id),eq(educationBundlesTable.centerId,req.params.centerId))).for("update").limit(1);if(!existing)throw new Error("BUNDLE");const purchased=(await tx.select({id:educationBundlePurchasesTable.id}).from(educationBundlePurchasesTable).where(eq(educationBundlePurchasesTable.bundleId,existing.id)).limit(1)).length>0;if((existing.published||purchased)&&(p.data.name!==undefined||p.data.description!==undefined||p.data.price!==undefined||p.data.courseIds!==undefined))throw new Error("IMMUTABLE");if(p.data.published){const ids=p.data.courseIds??(await tx.select({id:educationBundleCoursesTable.courseId}).from(educationBundleCoursesTable).where(eq(educationBundleCoursesTable.bundleId,existing.id))).map(x=>x.id);const valid=ids.length?await tx.select({id:coursesTable.id}).from(coursesTable).where(and(eq(coursesTable.centerId,req.params.centerId),inArray(coursesTable.id,ids),eq(coursesTable.published,true),eq(coursesTable.archived,false))):[];if(!(p.data.active??existing.active)||!ids.length||valid.length!==ids.length)throw new Error("COURSE");}const {courseIds,name,...updates}=p.data;const [bundle]=await tx.update(educationBundlesTable).set({...updates,...(name===undefined?{}:{title:name}),updatedAt:new Date()}).where(eq(educationBundlesTable.id,existing.id)).returning();if(courseIds){await tx.delete(educationBundleCoursesTable).where(eq(educationBundleCoursesTable.bundleId,bundle.id));await tx.insert(educationBundleCoursesTable).values(courseIds.map((courseId,sortOrder)=>({bundleId:bundle.id,courseId,sortOrder})));}return bundle;}).catch((e)=>e instanceof Error?e.message:null);if(!row)return res.status(404).json({error:"Paket nije pronađen ili kurs ne pripada centru."});if(typeof row==="string")return res.status(row==="IMMUTABLE"?409:400).json({error:row==="IMMUTABLE"?"Objavljen ili kupljen paket može samo da se arhivira.":"Paket mora sadržati aktivne kurseve centra."});res.json(bundleView(row));});
router.delete("/education/centers/:centerId/bundles/:id",async(req,res)=>{if(!await access(req,res,req.params.centerId))return;const [row]=await db.update(educationBundlesTable).set({active:false,published:false,updatedAt:new Date()}).where(and(eq(educationBundlesTable.id,req.params.id),eq(educationBundlesTable.centerId,req.params.centerId))).returning();if(!row){res.status(404).json({error:"Paket nije pronađen."});return;}res.status(204).send();});
router.get("/education/centers/:centerId/contacts",async(req,res)=>{if(!await access(req,res,req.params.centerId))return;res.json(await db.select().from(educationContactHistoryTable).where(eq(educationContactHistoryTable.centerId,req.params.centerId)).orderBy(asc(educationContactHistoryTable.createdAt)));});
router.post("/education/centers/:centerId/contacts",async(req,res)=>{const user=await access(req,res,req.params.centerId);if(!user)return;const p=z.object({learnerUserId:z.string().uuid().nullable().optional(),enrollmentId:z.string().uuid().nullable().optional(),channel:z.string().min(1),note:z.string().min(1)}).safeParse(req.body);if(!p.success)return bad(res,"Kontakt nije ispravan.");const row=await db.transaction(async tx=>{if(p.data.enrollmentId){const [enrollment]=await tx.select({userId:courseEnrollmentsTable.userId}).from(courseEnrollmentsTable).innerJoin(coursesTable,eq(coursesTable.id,courseEnrollmentsTable.courseId)).where(and(eq(courseEnrollmentsTable.id,p.data.enrollmentId),eq(coursesTable.centerId,req.params.centerId))).limit(1);if(!enrollment||p.data.learnerUserId&&enrollment.userId!==p.data.learnerUserId)throw new Error("CONTACT");}return (await tx.insert(educationContactHistoryTable).values({...p.data,centerId:req.params.centerId,actorUserId:user.id,learnerUserId:p.data.learnerUserId??null,enrollmentId:p.data.enrollmentId??null}).returning())[0];}).catch(()=>null);if(!row)return res.status(400).json({error:"Polaznik ili upis ne pripada ovom centru."});res.status(201).json(row);});
router.get("/education/centers/:centerId/crm",async(req,res)=>{if(!await access(req,res,req.params.centerId))return;const participantUserId=sql<string | null>`coalesce(${employeesTable.userId}, ${courseEnrollmentsTable.userId})`;const learnerName=sql<string>`max(coalesce(${employeesTable.name}, ${usersTable.firstName} || ' ' || ${usersTable.lastName}, 'Gost'))`;const learners=await db.select({userId:participantUserId,learnerName,count:sql<number>`count(*)::int`,completed:sql<number>`count(*) filter (where ${courseEnrollmentsTable.status}='completed')::int`}).from(courseEnrollmentsTable).innerJoin(coursesTable,eq(coursesTable.id,courseEnrollmentsTable.courseId)).leftJoin(employeesTable,eq(employeesTable.id,courseEnrollmentsTable.employeeId)).leftJoin(usersTable,eq(usersTable.id,participantUserId)).where(eq(coursesTable.centerId,req.params.centerId)).groupBy(participantUserId);res.json({learners});});
router.get("/education/centers/:centerId/instructors/performance",async(req,res)=>{if(!await access(req,res,req.params.centerId))return;const rows=await db.select({instructorId:coursesTable.instructorId,courses:sql<number>`count(distinct ${coursesTable.id})::int`,enrollments:sql<number>`count(${courseEnrollmentsTable.id})::int`,completions:sql<number>`count(*) filter (where ${courseEnrollmentsTable.status}='completed')::int`}).from(coursesTable).leftJoin(courseEnrollmentsTable,eq(courseEnrollmentsTable.courseId,coursesTable.id)).where(eq(coursesTable.centerId,req.params.centerId)).groupBy(coursesTable.instructorId);res.json({instructors:rows});});
router.post("/education/centers/:centerId/assistant",async(req,res)=>{if(!await access(req,res,req.params.centerId))return;const p=z.object({prompt:z.string().min(1).max(2000)}).safeParse(req.body);if(!p.success)return bad(res,"Pitanje nije ispravno.");const [stats]=await db.select({courses:sql<number>`count(*)::int`,learners:sql<number>`count(distinct ${courseEnrollmentsTable.userId})::int`}).from(coursesTable).leftJoin(courseEnrollmentsTable,eq(courseEnrollmentsTable.courseId,coursesTable.id)).where(eq(coursesTable.centerId,req.params.centerId));res.json({reply:`Na osnovu podataka vašeg centra: imate ${stats?.courses??0} kurseva i ${stats?.learners??0} polaznika. Za pitanje „${p.data.prompt}”, proverite raspored termina i napredak polaznika u centru.`,grounding:"Samo kursevi, termini i polaznici ovog edukativnog centra."});});
export default router;