-- PostgreSQL 16 SELECT/WITH designs only. Every statement is bounded, parameterized and attributable.
-- Each runnable section uses its own contiguous positional contract from sql-section-manifest.json.
-- D-01 / P-01 / PE-01
WITH scope AS (SELECT unnest($2::text[]) AS record_id) SELECT $1::text AS capture_id, $3::text AS chunk_id, scope.record_id, current_database() AS database_name, current_setting('server_version_num') AS server_version_num, current_setting('transaction_read_only') AS transaction_read_only FROM scope LIMIT 1000;
-- D-02 / P-02 / PE-02
-- Runnable supporting observation only; does not satisfy the composite PE-02 requirement.
WITH scope AS (SELECT * FROM jsonb_to_recordset($5::jsonb) AS b(record_id text,schema_name text,object_name text,parent_name text)) SELECT $1::text AS capture_id,$4::text AS chunk_id,scope.record_id,(c.oid IS NOT NULL) AS object_found,c.relname AS marker_relation,c.reltuples::bigint AS estimated_rows FROM scope LEFT JOIN pg_catalog.pg_namespace n ON n.nspname=scope.schema_name AND n.nspname=ANY($2::text[]) LEFT JOIN pg_catalog.pg_class c ON c.relnamespace=n.oid AND c.relname=scope.object_name AND c.relname=ANY($3::text[]) LIMIT 1000;
-- D-03 / P-03 / PE-03
-- Runnable supporting observation only; does not satisfy the composite PE-03 requirement.
WITH scope AS (SELECT * FROM jsonb_to_recordset($5::jsonb) AS b(record_id text,schema_name text,object_name text,parent_name text)) SELECT $1::text AS capture_id,$4::text AS chunk_id,scope.record_id,(c.oid IS NOT NULL) AS object_found,n.nspname,c.relname,c.relkind,pg_catalog.pg_get_userbyid(c.relowner) AS owner_name,substring(d.definition FROM 1 FOR 512) AS definition_excerpt,length(d.definition) AS definition_length FROM scope LEFT JOIN pg_catalog.pg_namespace n ON n.nspname=scope.schema_name AND n.nspname=ANY($2::text[]) LEFT JOIN pg_catalog.pg_class c ON c.relnamespace=n.oid AND c.relname=scope.object_name AND c.relname=ANY($3::text[]) LEFT JOIN LATERAL (SELECT pg_catalog.pg_get_expr(ad.adbin,ad.adrelid) AS definition FROM pg_catalog.pg_attrdef ad WHERE ad.adrelid=c.oid ORDER BY ad.adnum ASC LIMIT 1) d ON true LIMIT 1000;
-- D-04 / P-04 / PE-04
-- Runnable supporting observation only; does not satisfy the composite PE-04 requirement.
WITH scope AS (SELECT * FROM jsonb_to_recordset($5::jsonb) AS b(record_id text,schema_name text,object_name text,parent_name text)) SELECT $1::text AS capture_id,$4::text AS chunk_id,scope.record_id,(ix.indexrelid IS NOT NULL) AS object_found,c.relname,i.relname AS index_name,ix.indisvalid,ix.indisready,ix.indisunique FROM scope LEFT JOIN pg_catalog.pg_namespace n ON n.nspname=scope.schema_name AND n.nspname=ANY($2::text[]) LEFT JOIN pg_catalog.pg_class c ON c.relnamespace=n.oid AND c.relname=scope.parent_name AND c.relname=ANY($3::text[]) LEFT JOIN pg_catalog.pg_class i ON i.relnamespace=n.oid AND i.relname=scope.object_name AND i.relname=ANY($3::text[]) LEFT JOIN pg_catalog.pg_index ix ON ix.indrelid=c.oid AND ix.indexrelid=i.oid LIMIT 1000;
-- D-05 / P-05 / PE-05
-- D-05 PREFLIGHT (must run first; scan preparation is gated by target_exists=true for same capture/chunk/record).
WITH scope AS (SELECT * FROM jsonb_to_recordset($3::jsonb) AS b(record_id text,schema_name text,object_name text)) SELECT $1::text AS capture_id,$2::text AS chunk_id,scope.record_id,'preflight'::text AS phase,(n.oid IS NOT NULL AND c.oid IS NOT NULL AND pg_catalog.to_regclass('public.shipping_rules') IS NOT NULL)::boolean AS target_exists,NULL::bigint AS observed_rows_capped_at_two FROM scope LEFT JOIN pg_catalog.pg_namespace n ON n.nspname=scope.schema_name AND n.nspname='public' LEFT JOIN pg_catalog.pg_class c ON c.relnamespace=n.oid AND c.relname=scope.object_name AND c.relname='shipping_rules' WHERE scope.schema_name='public' AND scope.object_name='shipping_rules' LIMIT 1;
-- D-05 SCAN (prepare only after preflight target_exists=true for same capture/chunk/record; otherwise BLOCKED_PRECONDITION and do not prepare).
WITH scope AS (SELECT * FROM jsonb_to_recordset($3::jsonb) AS b(record_id text,schema_name text,object_name text)) SELECT $1::text AS capture_id,$2::text AS chunk_id,scope.record_id,'scan'::text AS phase,NULL::boolean AS target_exists,scan.observed_rows_capped_at_two FROM scope CROSS JOIN (SELECT count(*)::bigint AS observed_rows_capped_at_two FROM (SELECT 1 FROM public.shipping_rules LIMIT 2) bounded_rows) scan WHERE scope.schema_name='public' AND scope.object_name='shipping_rules' LIMIT 1;
-- D-06 / P-06 / PE-06
-- BLOCKED: ownership metadata cannot establish policy authorization or reversibility.

-- D-07 / P-07 / PE-07 (supporting observation only; blocked composite facts)
WITH scope AS (SELECT unnest($2::text[]) AS record_id), activity AS (SELECT count(*)::bigint AS observed_sessions_capped_at_201, count(*) >= 201 AS sample_truncated FROM (SELECT 1 FROM pg_catalog.pg_stat_activity WHERE datname=current_database() AND pid<>pg_catalog.pg_backend_pid() LIMIT 201) bounded_activity) SELECT $1::text AS capture_id,$3::text AS chunk_id,scope.record_id,activity.observed_sessions_capped_at_201,activity.sample_truncated FROM scope CROSS JOIN activity LIMIT 1000;
-- D-08 / P-08 / PE-08
-- Runnable supporting observation only; does not satisfy the composite PE-08 requirement.
WITH scope AS (SELECT * FROM jsonb_to_recordset($5::jsonb) AS b(record_id text,schema_name text,object_name text,parent_name text)) SELECT $1::text AS capture_id,$4::text AS chunk_id,scope.record_id,(p.oid IS NOT NULL) AS object_found,n.nspname,p.proname,substring(pg_catalog.pg_get_function_identity_arguments(p.oid) FROM 1 FOR 256) AS argument_excerpt FROM scope LEFT JOIN pg_catalog.pg_namespace n ON n.nspname=scope.schema_name AND n.nspname=ANY($2::text[]) LEFT JOIN pg_catalog.pg_proc p ON p.pronamespace=n.oid AND p.proname=scope.object_name AND p.proname=ANY($3::text[]) LIMIT 500;
-- D-09 / P-09 / PE-09 (recovery metadata; restore proof blocked)
WITH scope AS (SELECT unnest($2::text[]) AS record_id) SELECT $1::text AS capture_id, $3::text AS chunk_id, scope.record_id, 'recovery_state' AS result_kind, pg_catalog.pg_is_in_recovery()::text AS result_value, true AS bounded, false AS truncation_applied FROM scope LIMIT 1000;
-- D-10 / P-10 / PE-10
-- BLOCKED: reviewer identity, approval, evidence digest and disposition are non-database attestations. No SQL statement is permitted.
